# Generated by Django 4.2.3 on 2023-07-09 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_inventary_product_inventory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['placed_at']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title']},
        ),
    ]
