# Generated by Django 4.2.3 on 2023-07-13 16:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b0a89aba-9f6a-49af-a376-07adb8a84016'), primary_key=True, serialize=False),
        ),
    ]
