# Generated by Django 4.2.3 on 2023-07-20 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['placed_at'], 'permissions': [('cancel_order', 'can cancel order')]},
        ),
    ]
