# Generated by Django 4.2.3 on 2023-07-21 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'permissions': [{'can view history', 'view_history'}]},
        ),
    ]
